version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: coupon-book-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coupon_book_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coupon-book-network

  app:
    build: .
    container_name: coupon-book-api
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: coupon_book_service
      JWT_EXPIRATION_TIME: 7
      ENABLE_ORM_LOGS: true
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    networks:
      - coupon-book-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  coupon-book-network:
    driver: bridge
